### PR TITLE
Adding magic method support

### PR DESCRIPTION
**Pull request by aduh95**
Allows to use a magic method to create a children to an element:

```php
<?php
echo HtmlTag::div(['id'=>'google_ads'])->addClass('advertisement')->addElement()
	()->p('Hello World!')
	()->p()->addElement()
		()->b('You are looking for an answer?')
		()->br()
		()->a([
			'href'=>'http://google.fr/',
			'alt'=>'Search the web',
			])->text('Google')
		()->text(' has it!');
?>
```

This will output:

```html
<div id="google_ads" class="advertisement">
	<p>Hello World!</p>
	<p>
	<b>You are looking for an answer?</b>
	<br/>
	
	<a href="http://google.fr/" alt="Search the web">Google</a> has it!</p></div>
```

As you can see, the first argument of the magic methods (static or not) can be used to set the attributes. To achieve that, I've changed the `set` method.

It's not very intuitive to use `addElement` to add many elements, maybe we should consider to alias (or rename) it `append`, as in jQuery for example.

### CODE REVIEW

**Comment by Airmanbzh** [comment]
I like this idea too but I take some extra time to analyse it. I don't want to see any side effect on the existing code ;)

**Comment by therocis** [comment]
I've added this on my own extension of your code a few months ago and it works great with no side effect. I've implemented mine with the ability to set the text/value as the first argument, and the second - the array of attributes.

**Comment by aduh95** [comment]
@therocis My implementation does have the ability to set text/value as the second argument, doesn't it?

**Comment by therocis** [comment]
Sorry @aduh95  - I didn't look at your code. But great that we both think alike :)

**Comment by Airmanbzh** [comment]
Sorry to answer so late. I made some test and all seems ok to me :)

**Pull request merged**
